### ISSUE TITLE
Block node network interfaces through nft

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/demo#6]
input interface should be specified or all interfaces will be blocked

Extend : failures.py

**Comment by hossnys** [comment]
how this is going to be done as z-os is using nft not iptables and when list ports of node there is only 22 and 6379 ,, when try to drop 6379  it's still didn't reflect there on alerta ,so need to know how the agent of alerta is reporting that node is online or offline , to know which interface and port to block .

**Comment by muhamadazmy** [comment]
We need to first be exactly sure how Alreta detects the state of the machine! does it access a url of the robot? does it uses the redis client (I doubt).

Once we know that we can simply fake the failure by blocking this. We can't just try blocking ports.

An easy solution is to bring all the machine interfaces down. The robot might still try to recover from that state though.

**Comment by zaibon** [comment]
Alerta is just a service they is able to send alerts. Other services that need to send an alert have to walk over all the alerta services installed and use it to sends alerts.
Currently there is no services that does that yet.

Regarding node down. Doing it from the node is not going to wor obviously. We Needs to have something else then the node, maybe the farmer bot, That watch the node status and sends alerts

**Comment by hossnys** [comment]
here is the [script](https://gist.github.com/hossnys/32264bff62c2b8fc781a142a2c7fe2e0) which can simulate blocking network ports (redis - z-robot - zdb ) for z-os node using nftables

**Comment by hossnys** [comment]
here is the updated [script](https://github.com/threefoldtech/minio/blob/network_failures/test/failures_testsuite/utils/alerta_failures_actions.py)
for all actions in issue #7 that depends on this issue,,, but for management interface failure simulation be careful that node will need to be rebooted over ipmi interface if you get management interface down so i commented the two function doing this in the script.
