### ISSUE TITLE
Demo alterting

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/demo#7]
child of threefoldtech/home#23

Test | Requires | Finished
-- | -- | --
Simulate node failure | requires #6  | <ul><li>[ ✔ ] </li></ul>
Simulate an hdd disk failure | requires #3 | <ul><li>[ ✔ ] </li></ul>
Simulate an ssd disk failure | requires #3 | <ul><li>[ ✔ ]</li></ul>
Simulate network failure of the management nic | requires #6 | <ul><li>[ ✔ ] </li></ul>
Simulate network failure of one of the backend nics | requires #6  | <ul><li>[ ✔ ] </li></ul>
Simulate network failure of both backend nics | requires #6 | <ul><li>[ ✔ ]</li></ul>

**Comment by ramezsaeed** [comment]
What we got from Sarah regarding Alerta services
the only  supported alerts now are:
    1- node 0-robot down
    2- ZDB down

and these alerts not even in the acceptance tests docs

so please discuss regarding the Alerts in the acceptance tests docs

@zaibon @rkhamis @serboctor

**Comment by serboctor** [comment]
@ramezsaeed  Not when 0-robot is down, when a vdisk or zerodb are down, those are the two scenarios I said are implemented.

**Comment by ramezsaeed** [comment]
Thnx @serboctor

**Comment by zaibon** [comment]
Vdisk and zerodb runs on top of HDD and SSD, so there you have it. 
Regarding network failure, we don't have a solution for it yet. Cause it needs to happens from outside the node otherwise this is useless, same for node failure.
These things probably needs to be monitor from the farmer bot or something

**Comment by rkhamis** [comment]
@ramezsaeed ssd should be detectable with this PR: https://github.com/threefoldtech/0-templates/pull/222

network still pending indeed

**Comment by rkhamis** [comment]
Blocked on detecting network interfaces down

**Comment by zaibon** [comment]
regarding network monitoring, I don't think this is hard to do.
For the management nic, we can add a monitoring action in the node template that check the state of the zerotier nic.
For the backend nics, we can implement that in the network template. and check the state of the nic created for the backplane.

**Comment by ramezsaeed** [comment]
![photo_2018-11-25_21-23-33](https://user-images.githubusercontent.com/16083592/48983533-ab391280-f0f8-11e8-9f03-2e17bebe6b14.jpg)
![photo_2018-11-25_21-23-29](https://user-images.githubusercontent.com/16083592/48983534-abd1a900-f0f8-11e8-8421-6168037b387a.jpg)
![photo_2018-11-25_21-23-22](https://user-images.githubusercontent.com/16083592/48983535-ac6a3f80-f0f8-11e8-9175-f0ee85aa4414.jpg)
![photo_2018-11-25_21-23-14](https://user-images.githubusercontent.com/16083592/48983536-ad02d600-f0f8-11e8-9631-bdc66fb06684.jpg)

**Comment by ramezsaeed** [comment]
https://docs.grid.tf/threefold/proj_bancadati/src/branch/master/testing/s3_testing/utils/alerta_failures_actions.py
